---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: metallb-config
data:
  config: |
    address-pools:
    - name: metallb-config
      protocol: layer2
      addresses:
      - 172.17.255.1-172.17.255.250