name: "test local repo script"
on: [push, pull_request]

jobs:
  lint-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Kind
      run: ./bin/kind-local-setup.sh install
    - name: Start Kind
      run: ./bin/kind-local-setup.sh start
    - name: Run test
      run: ./k8s/busybox/test.sh
